export type DesignStyle = "modern" | "japandi" | "scandinavian" | "industrial" | "traditional" | "mid-century" | "bohemian" | "coastal" | "luxury" | "minimal" | "eclectic";
export type DesignGoal = "refresh" | "redecorate" | "rearrange" | "stage" | "maximize-storage" | "make-larger" | "make-cozier";
export interface RoomContext { roomId: string; roomType: string; imageUrls: string[]; style?: DesignStyle; goals: DesignGoal[]; userPrompt?: string; budget?: number; currency?: string; preserveObjectIds: string[]; }
export interface DesignerObject { id: string; label: string; confidence: number; bbox: { x: number; y: number; width: number; height: number }; fixed: boolean; movable: boolean; removable: boolean; }
export interface DesignDecision { category: string; rationale: string; priority: number; confidence: number; }
export interface ArchitectureLock { preserveWalls: boolean; preserveWindows: boolean; preserveDoors: boolean; preserveFloor: boolean; preserveCeiling: boolean; preserveCameraPerspective: boolean; }
export const DEFAULT_ARCHITECTURE_LOCK: ArchitectureLock = { preserveWalls: true, preserveWindows: true, preserveDoors: true, preserveFloor: true, preserveCeiling: true, preserveCameraPerspective: true };
export const STYLE_VOCABULARY: Record<DesignStyle, string[]> = { modern: ["clean lines", "soft neutrals", "functional furniture"], japandi: ["natural wood", "quiet contrast", "organic textures"], scandinavian: ["light woods", "airy textiles", "simple forms"], industrial: ["metal accents", "aged textures", "dark contrast"], traditional: ["symmetry", "classic silhouettes", "layered textiles"], "mid-century": ["warm wood", "geometric forms", "vintage accents"], bohemian: ["layered textiles", "plants", "handcrafted accents"], coastal: ["light palette", "natural fibers", "blue-green accents"], luxury: ["refined materials", "balanced lighting", "sculptural furniture"], minimal: ["negative space", "few objects", "precise alignment"], eclectic: ["mixed eras", "intentional contrast", "curated objects"] };
export function normalizeDesignerRequest(input: Partial<{ room: RoomContext; requestedStyle: DesignStyle; requestedChanges: string[]; preserveFurniture: boolean; preserveArchitecture: boolean; outputCount: number }>) { if (!input.room) throw new Error("ROOM_CONTEXT_REQUIRED"); return { room: input.room, requestedStyle: input.requestedStyle ?? "modern", requestedChanges: (input.requestedChanges ?? []).slice(0, 12), preserveFurniture: input.preserveFurniture ?? true, preserveArchitecture: input.preserveArchitecture ?? true, outputCount: Math.min(6, Math.max(1, input.outputCount ?? 3)) }; }
export function styleCompatibility(a: DesignStyle, b: DesignStyle) { if (a === b) return 1; const compatible: Partial<Record<DesignStyle, DesignStyle[]>> = { modern: ["minimal", "scandinavian", "mid-century", "luxury"], japandi: ["minimal", "scandinavian", "modern"], scandinavian: ["modern", "japandi", "mid-century"], luxury: ["modern", "traditional", "minimal"] }; return compatible[a]?.includes(b) ? 0.78 : 0.35; }
export function buildPreservationRules(objects: Array<{ id: string; label: string }>, preserveAll: boolean) { return objects.map((object) => ({ objectId: object.id, mode: preserveAll ? "keep" as const : "replace" as const, reason: preserveAll ? "User requested existing furniture preservation." : "User allowed redesign." })); }
export function buildDesignDecisions(room: RoomContext, lock = DEFAULT_ARCHITECTURE_LOCK): DesignDecision[] { const decisions: DesignDecision[] = [{ category: "architecture", rationale: lock.preserveCameraPerspective ? "Keep the camera perspective and fixed structure stable." : "Architecture may be explored as a remodel concept.", priority: 1, confidence: 0.98 }, { category: "layout", rationale: room.goals.includes("rearrange") ? "Prioritize circulation and a clearer furniture path." : "Balance the room around its existing focal point.", priority: 2, confidence: 0.86 }, { category: "style", rationale: `Use ${room.style ?? "modern"} cues: ${(STYLE_VOCABULARY[room.style ?? "modern"] ?? STYLE_VOCABULARY.modern).join(", ")}.`, priority: 3, confidence: 0.84 }]; if (room.budget) decisions.push({ category: "budget", rationale: `Stay near the ${room.currency ?? "USD"} ${room.budget.toLocaleString()} target.`, priority: 4, confidence: 0.8 }); return decisions; }
