export const API_CONFIG = { baseUrl: (process.env.EXPO_PUBLIC_API_URL ?? "").replace(/\/$/, ""), timeoutMs: 15000 } as const;
export function apiUrl(path: string) { return `${API_CONFIG.baseUrl}/${path.replace(/^\//, "")}`; }
export class ApiError extends Error { constructor(public status: number, public code: string, message: string) { super(message); this.name = "ApiError"; } }
export async function request<T>(path: string, init: RequestInit = {}): Promise<T> { if (!API_CONFIG.baseUrl) throw new ApiError(0, "API_NOT_CONFIGURED", "The service is not connected yet."); const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), API_CONFIG.timeoutMs); try { const response = await fetch(apiUrl(path), { ...init, signal: controller.signal, headers: { Accept: "application/json", "Content-Type": "application/json", ...(init.headers ?? {}) } }); const text = await response.text(); let body: unknown = null; try { body = text ? JSON.parse(text) : null; } catch { body = null; } if (!response.ok) { const message = body && typeof body === "object" && "message" in body ? String(body.message) : `Request failed (${response.status})`; throw new ApiError(response.status, `HTTP_${response.status}`, message); } return body as T; } catch (error) { if (error instanceof ApiError) throw error; if (error instanceof DOMException && error.name === "AbortError") throw new ApiError(408, "TIMEOUT", "The request took too long. Please try again."); throw new ApiError(0, "NETWORK_ERROR", "We couldn’t reach the service. Please check your connection."); } finally { clearTimeout(timeout); } }
export interface Room { id: string; name: string; type: string; photoUrls: string[]; createdAt: string; updatedAt: string; }
export interface Design { id: string; roomId: string; title: string; imageUrl: string; style: string; createdAt: string; }
export interface GenerationJob { id: string; status: "queued" | "running" | "complete" | "failed"; progress: number; designId?: string; error?: string; }
export interface CatalogItem { id: string; title: string; category: string; price: number; imageUrl: string; url: string; }
export const roomApi = { list: () => request<Room[]>("/v1/rooms"), get: (id: string) => request<Room>(`/v1/rooms/${encodeURIComponent(id)}`), create: (input: Omit<Room, "id" | "createdAt" | "updatedAt">) => request<Room>("/v1/rooms", { method: "POST", body: JSON.stringify(input) }) };
export const designApi = { list: (roomId?: string) => request<Design[]>(roomId ? `/v1/designs?roomId=${encodeURIComponent(roomId)}` : "/v1/designs"), get: (id: string) => request<Design>(`/v1/designs/${encodeURIComponent(id)}`) };
export const generationApi = { start: (input: { roomId: string; style: string; request: string; budget?: number }) => request<GenerationJob>("/v1/generations", { method: "POST", body: JSON.stringify(input) }), get: (id: string) => request<GenerationJob>(`/v1/generations/${encodeURIComponent(id)}`) };
export const catalogApi = { search: (query: string, category?: string) => request<CatalogItem[]>(`/v1/catalog/search?q=${encodeURIComponent(query)}${category ? `&category=${encodeURIComponent(category)}` : ""}`) };
export const appServices = { rooms: roomApi, designs: designApi, generations: generationApi, catalog: catalogApi };
