import type { GenerationJob } from "./api";

export type GenerationPhase = "idle" | "polling" | "paused" | "complete" | "failed";
export interface GenerationLifecycleState { phase: GenerationPhase; job: GenerationJob | null; attempts: number; error: string | null; pauseReason: "offline" | "user" | null; }
export const initialGenerationLifecycle: GenerationLifecycleState = { phase: "idle", job: null, attempts: 0, error: null, pauseReason: null };
export function beginGenerationLifecycle(job: GenerationJob): GenerationLifecycleState { return { phase: "polling", job, attempts: 0, error: null, pauseReason: null }; }
export function pauseGenerationLifecycle(state: GenerationLifecycleState, reason: "offline" | "user" = "user"): GenerationLifecycleState { return state.phase === "polling" ? { ...state, phase: "paused", pauseReason: reason } : state; }
export function resumeGenerationLifecycle(state: GenerationLifecycleState): GenerationLifecycleState { return state.phase === "paused" ? { ...state, phase: "polling", pauseReason: null } : state; }
export function resumeIfOfflinePause(state: GenerationLifecycleState, online: boolean): GenerationLifecycleState { return online && state.phase === "paused" && state.pauseReason === "offline" ? resumeGenerationLifecycle(state) : state; }
export function reduceGenerationJob(state: GenerationLifecycleState, job: GenerationJob): GenerationLifecycleState { if (job.status === "complete") return { ...state, phase: "complete", job, error: null }; if (job.status === "failed") return { ...state, phase: "failed", job, error: job.error ?? "Generation could not be completed." }; return { ...state, phase: "polling", job, attempts: state.attempts + 1, error: null, pauseReason: null }; }
export function recordGenerationPollingError(state: GenerationLifecycleState, error: unknown): GenerationLifecycleState { return { ...state, phase: "failed", error: error instanceof Error ? error.message : "We couldn’t check generation status.", pauseReason: null }; }
export function shouldPollGeneration(state: GenerationLifecycleState) { return state.phase === "polling" && Boolean(state.job) && state.job?.status !== "complete" && state.job?.status !== "failed"; }
export function generationPollDelay(attempt: number) { return Math.min(8000, 1200 + Math.max(0, attempt) * 600); }
export function generationCopy(state: GenerationLifecycleState) { if (state.phase === "paused" && state.pauseReason === "offline") return { title: "Generation paused offline", body: "Your progress is safe. We’ll resume checking automatically when you’re back online.", action: "Waiting for connection" }; if (state.phase === "paused") return { title: "Generation paused", body: "Your progress is safe. Resume when you’re ready.", action: "Resume" }; if (state.phase === "failed") return { title: "We couldn’t finish that", body: state.error ?? "Try checking the connection, then retry the generation.", action: "Retry" }; if (state.phase === "complete") return { title: "Your room is ready", body: "Architecture and key furniture were kept in the design direction.", action: "View concept" }; return { title: "Understanding your space…", body: "We’re preserving your architecture and finding the best next move for the room.", action: "Pause" }; }
