import AsyncStorage from "@react-native-async-storage/async-storage";
import { runtimePolicy } from "./runtime";

export interface RenderedVersion { id: string; imageUri: string; createdAt: string; }
export interface RefinementRecord { id: string; label: string; createdAt: string; versionId?: string; }
export interface SavedDesign { id: string; title: string; style: string; roomType: string; imageUri: string; updatedAt: string; conceptCount: number; budget?: number; refinements?: RefinementRecord[]; versions?: RenderedVersion[]; }
export const SAVED_DESIGNS_KEY = "rerroom.saved-designs.v1";
export const demoSavedDesigns: SavedDesign[] = [{ id: "living-room-refresh", title: "Living room refresh", style: "Modern warm", roomType: "Living room", imageUri: "demo://living-room", updatedAt: "Today", conceptCount: 2, budget: 1200, refinements: [{ id: "initial", label: "Original concept generated", createdAt: "Today", versionId: "version-initial" }], versions: [{ id: "version-initial", imageUri: "demo://living-room", createdAt: "Today" }] }];

function normalizeDesign(item: unknown): SavedDesign | null { if (!item || typeof item !== "object") return null; const value = item as Partial<SavedDesign>; if (typeof value.id !== "string" || typeof value.title !== "string") return null; const refinements = Array.isArray(value.refinements) ? value.refinements.filter((entry): entry is RefinementRecord => Boolean(entry && typeof entry === "object" && typeof (entry as RefinementRecord).id === "string" && typeof (entry as RefinementRecord).label === "string" && typeof (entry as RefinementRecord).createdAt === "string")).map((entry) => ({ ...entry, versionId: typeof entry.versionId === "string" ? entry.versionId : undefined })) : undefined; const versions = Array.isArray(value.versions) ? value.versions.filter((entry): entry is RenderedVersion => Boolean(entry && typeof entry === "object" && typeof (entry as RenderedVersion).id === "string" && typeof (entry as RenderedVersion).imageUri === "string" && typeof (entry as RenderedVersion).createdAt === "string")) : undefined; return { id: value.id, title: value.title, style: typeof value.style === "string" ? value.style : "Contemporary", roomType: typeof value.roomType === "string" ? value.roomType : "Room", imageUri: typeof value.imageUri === "string" ? value.imageUri : "demo://room", updatedAt: typeof value.updatedAt === "string" ? value.updatedAt : "Recently", conceptCount: typeof value.conceptCount === "number" ? value.conceptCount : 1, budget: typeof value.budget === "number" && value.budget > 0 ? value.budget : undefined, refinements, versions }; }
export function parseSavedDesigns(raw: string | null): SavedDesign[] { if (!raw) return []; try { const value: unknown = JSON.parse(raw); return Array.isArray(value) ? value.map(normalizeDesign).filter((item): item is SavedDesign => item !== null) : []; } catch { return []; } }
export async function loadSavedDesigns(): Promise<SavedDesign[]> { try { const designs = parseSavedDesigns(await AsyncStorage.getItem(SAVED_DESIGNS_KEY)); return designs.length ? designs : runtimePolicy.allowDemoData ? demoSavedDesigns : []; } catch { return runtimePolicy.allowDemoData ? demoSavedDesigns : []; } }
export async function saveSavedDesigns(designs: SavedDesign[]) { await AsyncStorage.setItem(SAVED_DESIGNS_KEY, JSON.stringify(designs.slice(0, 50))); }
export async function upsertSavedDesign(design: SavedDesign) { const current = await loadSavedDesigns(); const next = [design, ...current.filter((item) => item.id !== design.id)]; await saveSavedDesigns(next); return next; }
export async function appendRefinement(id: string, refinement: RefinementRecord, version?: RenderedVersion) { const current = await loadSavedDesigns(); const next = current.map((design) => design.id === id ? { ...design, updatedAt: refinement.createdAt, refinements: [...(design.refinements ?? []), { ...refinement, versionId: version?.id ?? refinement.versionId }].slice(-20), versions: version ? [...(design.versions ?? []), version].slice(-20) : design.versions } : design); await saveSavedDesigns(next); return next.find((design) => design.id === id) ?? null; }
export async function removeSavedDesign(id: string) { const next = (await loadSavedDesigns()).filter((design) => design.id !== id); await saveSavedDesigns(next); return next; }
export async function updateSavedDesignBudget(id: string, budget: number) { const next = (await loadSavedDesigns()).map((design) => design.id === id ? { ...design, budget } : design); await saveSavedDesigns(next); return next.find((design) => design.id === id) ?? null; }
