export type ShopCategory = "All" | "Lighting" | "Textiles" | "Decor" | "Storage";
export type ShopSort = "recommended" | "price-low" | "price-high";
export type StockStatus = "in-stock" | "low-stock" | "backorder";
export interface ShopProduct { id: string; name: string; category: Exclude<ShopCategory, "All">; price: number; detail: string; palette: string; fit: string; description: string; dimensions: string; retailer: string; retailerUrl: string; stockStatus: StockStatus; priceUpdatedAt: string; }
export const shopCategories: ShopCategory[] = ["All", "Lighting", "Textiles", "Decor", "Storage"];
export const shopProducts: ShopProduct[] = [
  { id: "linen-floor-lamp", name: "Linen floor lamp", category: "Lighting", price: 128, detail: "Soft ambient light", palette: "#D6B99B", fit: "Works with your warm direction", description: "A linen-shaded floor lamp that layers gentle light without taking over the room.", dimensions: "58 in high · Linen shade", retailer: "Northline Home", retailerUrl: "https://example.com/northline/linen-floor-lamp", stockStatus: "in-stock", priceUpdatedAt: "2026-08-20T09:00:00.000Z" },
  { id: "wool-loop-rug", name: "Wool loop rug", category: "Textiles", price: 240, detail: "Low-pile · 5 × 7 ft", palette: "#B6A28F", fit: "Defines the conversation zone", description: "A quiet, low-pile foundation that gives the seating area a collected, grounded feel.", dimensions: "5 × 7 ft · Low pile", retailer: "Hearth & Loom", retailerUrl: "https://example.com/hearth/wool-loop-rug", stockStatus: "low-stock", priceUpdatedAt: "2026-08-21T14:30:00.000Z" },
  { id: "ceramic-vessel", name: "Hand-thrown vessel", category: "Decor", price: 46, detail: "Matte clay finish", palette: "#C47E61", fit: "Adds a quiet sculptural note", description: "A hand-thrown clay accent for open shelving, consoles, and the spaces in between.", dimensions: "9 in high · Matte clay", retailer: "Studio Forma", retailerUrl: "https://example.com/studio-forma/ceramic-vessel", stockStatus: "in-stock", priceUpdatedAt: "2026-08-18T11:15:00.000Z" },
  { id: "oak-wall-console", name: "Oak wall console", category: "Storage", price: 395, detail: "Cable-ready · 48 in", palette: "#90745C", fit: "Keeps the walkway visually clear", description: "A slim oak console with generous concealed storage and a profile made for smaller footprints.", dimensions: "48 × 14 in · Cable-ready", retailer: "Common Ground", retailerUrl: "https://example.com/common-ground/oak-console", stockStatus: "backorder", priceUpdatedAt: "2026-08-10T16:00:00.000Z" },
  { id: "cotton-cushion", name: "Washed cotton cushion", category: "Textiles", price: 34, detail: "Stone · 20 × 20 in", palette: "#D9D0C1", fit: "Layers texture without clutter", description: "A washed cotton cushion that adds tactile depth while keeping the palette soft and flexible.", dimensions: "20 × 20 in · Stone cotton", retailer: "Northline Home", retailerUrl: "https://example.com/northline/cotton-cushion", stockStatus: "in-stock", priceUpdatedAt: "2026-08-19T08:45:00.000Z" },
];
export function filterShopProducts(category: ShopCategory, maxPrice = Number.POSITIVE_INFINITY) { return shopProducts.filter((item) => (category === "All" || item.category === category) && item.price <= maxPrice); }
export function sortShopProducts(products: ShopProduct[], sort: ShopSort) { return [...products].sort((a, b) => sort === "price-low" ? a.price - b.price : sort === "price-high" ? b.price - a.price : a.id.localeCompare(b.id)); }
export function formatShopPrice(price: number) { return `$${price.toLocaleString("en-US")}`; }
export function recommendationCopy(product: ShopProduct, roomStyle = "Modern warm") { return `${product.name} supports a ${roomStyle.toLowerCase()} direction by ${product.fit.toLowerCase()}.`; }
export function budgetAlternatives(product: ShopProduct, maxPrice = product.price) { return shopProducts.filter((item) => item.id !== product.id && item.category === product.category && item.price < maxPrice).sort((a, b) => b.price - a.price).slice(0, 2); }
export function savingsAmount(originalPrice: number, alternativePrice: number) { return Math.max(0, originalPrice - alternativePrice); }
export function savingsPercent(originalPrice: number, alternativePrice: number) { return originalPrice <= 0 ? 0 : Math.round((savingsAmount(originalPrice, alternativePrice) / originalPrice) * 100); }
export function savingsCopy(originalPrice: number, alternativePrice: number) { const amount = savingsAmount(originalPrice, alternativePrice); const percent = savingsPercent(originalPrice, alternativePrice); return amount > 0 ? `Save ${formatShopPrice(amount)} · ${percent}% less` : "Same price"; }
export function shortlistSavings(products: ShopProduct[]) { return products.reduce((total, product) => { const categoryHigh = Math.max(...shopProducts.filter((item) => item.category === product.category).map((item) => item.price), product.price); return total + savingsAmount(categoryHigh, product.price); }, 0); }
export function shortlistSavingsCopy(amount: number, itemCount: number) { return amount > 0 ? `Up to ${formatShopPrice(amount)} in room-level savings across ${itemCount} ${itemCount === 1 ? "piece" : "pieces"}` : "Your shortlist is already at the top of each category"; }
export function shortlistTotal(products: ShopProduct[]) { return products.reduce((total, product) => total + product.price, 0); }
export function budgetDelta(total: number, budget: number) { return budget - total; }
export function budgetStatusCopy(total: number, budget: number) { const delta = budgetDelta(total, budget); return delta >= 0 ? `${formatShopPrice(delta)} left in your room budget` : `${formatShopPrice(Math.abs(delta))} over your room budget`; }
export function stockStatusCopy(status: StockStatus) { return status === "in-stock" ? "In stock" : status === "low-stock" ? "Low stock" : "Available to order"; }
export function stockStatusTone(status: StockStatus) { return status === "in-stock" ? "positive" : status === "low-stock" ? "caution" : "neutral" as const; }
export function priceFreshnessCopy(updatedAt: string, now: number) { const ageDays = Math.max(0, Math.floor((now - Date.parse(updatedAt)) / 86_400_000)); return ageDays === 0 ? "Price checked today" : ageDays === 1 ? "Price checked yesterday" : `Price checked ${ageDays} days ago`; }
export function priceFreshnessIsRecent(updatedAt: string, now: number, maxAgeDays = 7) { return now - Date.parse(updatedAt) <= maxAgeDays * 86_400_000; }
import type { Connectivity } from "./networkCore";

export type PriceRefreshState = "idle" | "refreshing" | "updated" | "stale";
export function canRefreshPrice(connectivity: Connectivity) { return connectivity === "online"; }
export function priceRefreshOfflineCopy(connectivity: Connectivity) { return connectivity === "offline" ? "Reconnect to check the retailer price" : connectivity === "unknown" ? "Checking connection before refresh" : "Refresh retailer price"; }
export function shouldAutoRefreshPrice(previous: Connectivity, current: Connectivity, pending: boolean) { return pending && previous !== "online" && current === "online"; }
export function priceRefreshAnnouncement(trigger: "manual" | "reconnect", state: PriceRefreshState) { if (trigger === "reconnect" && state === "refreshing") return "Connection restored. Refreshing the retailer price now."; if (state === "updated") return trigger === "reconnect" ? "Retailer price refreshed after reconnecting." : "Retailer price refreshed."; if (state === "stale") return "Retailer price still needs a recheck."; return ""; }
export function priceRefreshChipCopy(state: PriceRefreshState) { return state === "refreshing" ? "Refreshing after reconnect" : state === "updated" ? "Refreshed after reconnect" : state === "stale" ? "Recheck retailer price" : ""; }
export function priceRefreshExactTime(timestamp: number) { return `${new Date(timestamp).toISOString().slice(0, 16).replace("T", " ")} UTC`; }
export function priceRefreshLocalTime(timestamp: number, timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone, hour12 = true) { return new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", hour12, timeZone }).format(new Date(timestamp)); }
export function priceRefreshTimeZoneLabel(timestamp: number, timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone) { const part = new Intl.DateTimeFormat("en-US", { timeZone, timeZoneName: "short" }).formatToParts(new Date(timestamp)).find((item) => item.type === "timeZoneName"); return part?.value ?? timeZone; }
export function priceRefreshTimeCopy(timestamp: number, timeZone?: string, format: "12h" | "24h" = "12h") { return `${priceRefreshLocalTime(timestamp, timeZone, format === "12h")} (${priceRefreshTimeZoneLabel(timestamp, timeZone)}) · ${priceRefreshExactTime(timestamp)}`; }
export function priceRefreshCopy(state: PriceRefreshState) { return state === "refreshing" ? "Checking retailer price…" : state === "updated" ? "Price checked just now" : state === "stale" ? "Retailer price needs a recheck" : "Refresh retailer price"; }
export function priceRefreshResult(updatedAt: string, now: number): PriceRefreshState { return priceFreshnessIsRecent(updatedAt, now) ? "updated" : "stale"; }
