import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { loadSavedDesigns, type SavedDesign } from "@/services/savedDesigns";
import { activeHistoryEntry, findSavedRoom, renderedUriForHistory, selectHistoryEntry, toRoomDetail, type RoomDetailModel } from "@/services/roomDetails";
import { classifyRoomLoadError, roomLoadCopy, type RoomLoadErrorKind } from "@/services/roomLoad";
import { connectivityCopy } from "@/services/networkCore";
import { useConnectivity } from "@/services/network";

export default function RoomDetailScreen() {
  const colors = useColors();
  const connectivity = useConnectivity();
  const connectionCopy = connectivityCopy(connectivity);
  const { id } = useLocalSearchParams<{ id: string }>();
  const [model, setModel] = useState<RoomDetailModel | null>(null);
  const [loading, setLoading] = useState(true);
  const [restoredLabel, setRestoredLabel] = useState<string | null>(null);
  const [loadError, setLoadError] = useState(false);
  const [loadErrorKind, setLoadErrorKind] = useState<RoomLoadErrorKind>("unknown");
  useEffect(() => { let active = true; setLoading(true); setLoadError(false); loadSavedDesigns().then((items) => { const design = findSavedRoom(items, id ?? ""); if (active && design) setModel(toRoomDetail(design)); }).catch((error) => { if (active) { setLoadErrorKind(classifyRoomLoadError(error)); setLoadError(true); } }).finally(() => active && setLoading(false)); return () => { active = false; }; }, [id]);
  const loadCopy = roomLoadCopy(loadErrorKind);
  if (loading) return <ScreenContainer><View style={styles.state}><ActivityIndicator color={colors.primary} /><Text style={[styles.stateText, { color: colors.muted }]}>Loading room details…</Text></View></ScreenContainer>;
  if (loadError) return <ScreenContainer><View style={styles.state}><Ionicons name={connectivity === "offline" ? "cloud-offline-outline" : "alert-circle-outline"} size={32} color={colors.error} /><Text style={[styles.title, { color: colors.foreground }]}>{loadCopy.title}</Text><Text style={[styles.stateText, { color: colors.muted }]}>{connectivity === "offline" ? "You’re offline. Reconnect, then try again to load this room." : loadCopy.body}</Text><Pressable accessibilityRole="button" accessibilityLabel="Retry loading room" accessibilityHint={connectivity === "offline" ? "Reconnect to the internet before retrying" : undefined} onPress={() => { setLoadError(false); setLoading(true); loadSavedDesigns().then((items) => { const design = findSavedRoom(items, id ?? ""); if (design) setModel(toRoomDetail(design)); }).catch((error) => { setLoadErrorKind(classifyRoomLoadError(error)); setLoadError(true); }).finally(() => setLoading(false)); }} style={[styles.primary, { backgroundColor: colors.primary }]}><Text style={styles.primaryText}>{connectivity === "offline" ? "Try again when online" : "Try again"}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Back to rooms" onPress={() => router.replace("/(tabs)/rooms")}><Text style={[styles.restored, { color: colors.primary }]}>Back to My rooms</Text></Pressable></View></ScreenContainer>;
  if (!model) return <ScreenContainer><View style={styles.state}><Ionicons name="home-outline" size={32} color={colors.primary} /><Text style={[styles.title, { color: colors.foreground }]}>Room not found</Text><Pressable accessibilityRole="button" onPress={() => router.replace("/(tabs)/rooms")} style={[styles.primary, { backgroundColor: colors.primary }]}><Text style={styles.primaryText}>Back to My rooms</Text></Pressable></View></ScreenContainer>;
  const { design, history, preservationNote } = model;
  const activeEntry = activeHistoryEntry(model);
  const previewUri = renderedUriForHistory(design, activeEntry);
  function restoreEntry(entryId: string) { const next = selectHistoryEntry(model!, entryId); setModel(next); setRestoredLabel(activeHistoryEntry(next)?.label ?? null); }
    return <ScreenContainer><ScrollView contentContainerStyle={styles.content}><View style={styles.header}>
<Pressable accessibilityRole="button" accessibilityLabel="Back to rooms" hitSlop={10} onPress={() => router.back()}><Ionicons name="chevron-back" size={25} color={colors.foreground} /></Pressable><Text style={[styles.step, { color: colors.primary }]}>SAVED ROOM</Text><View style={{ width: 25 }} /></View>{connectivity !== "online" ? <View accessibilityRole="text" accessibilityLabel={`${connectionCopy.label}: ${connectionCopy.message}`} style={[styles.connectionBanner, { backgroundColor: colors.surface, borderColor: colors.border }]}><Ionicons name={connectivity === "offline" ? "cloud-offline-outline" : "radio-outline"} size={17} color={connectivity === "offline" ? colors.warning : colors.muted} /><Text style={[styles.connectionText, { color: colors.foreground }]}>{connectionCopy.message}</Text></View> : null}<Text style={[styles.title, { color: colors.foreground }]}>{design.title}</Text>
<Text style={[styles.subtitle, { color: colors.muted }]}>{design.style} · {design.roomType} · {design.updatedAt}</Text><View style={[styles.preview, { backgroundColor: "#C7B5A4" }]}>{previewUri.startsWith("demo://") ? <><View style={styles.window} /><View style={styles.sofa} /><View style={styles.plant} /></> : <Image source={{ uri: previewUri }} style={styles.photo} />}<View style={styles.badge}><Ionicons name="sparkles" size={13} color="#FFFDF9" /><Text style={styles.badgeText}>{design.conceptCount} CONCEPTS</Text></View></View><View style={[styles.note, { backgroundColor: colors.surface, borderColor: colors.border }]}><Ionicons name="shield-checkmark-outline" size={20} color={colors.primary} /><Text style={[styles.noteText, { color: colors.foreground }]}>{preservationNote}</Text></View><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Refinement history</Text>{history.map((item) => <Pressable key={item.id} accessibilityRole="button" accessibilityLabel={`Restore ${item.label}${item.versionId ? ", view rendered version" : ""}`} accessibilityState={{ selected: item.active }} onPress={() => restoreEntry(item.id)} style={({ pressed }) => [styles.history, { borderBottomColor: colors.border }, item.active && styles.activeHistory, pressed && styles.pressed]}><View style={[styles.dot, { backgroundColor: item.active ? colors.primary : colors.border }]} /><View style={{ flex: 1 }}><Text style={[styles.historyLabel, { color: colors.foreground }]}>{item.label}</Text><Text style={[styles.historyDate, { color: colors.muted }]}>{item.createdAt}</Text></View><Ionicons name={item.active ? "checkmark-circle" : "chevron-forward"} size={19} color={item.active ? colors.primary : colors.muted} /></Pressable>)}{restoredLabel ? <Text style={[styles.restored, { color: colors.primary }]}>Restored: {restoredLabel}</Text> : activeEntry ? <Text style={[styles.restored, { color: colors.muted }]}>Current direction: {activeEntry.label}</Text> : null}<Pressable accessibilityRole="button" accessibilityLabel="Refine this room" onPress={() => router.push({ pathname: "/(tabs)/create", params: { roomId: design.id, historyId: activeEntry?.id ?? "initial", historyLabel: activeEntry?.label ?? "Original concept generated" } })} style={({ pressed }) => [styles.primary, { backgroundColor: colors.primary }, pressed && styles.pressed]}><Ionicons name="sparkles-outline" size={18} color="#FFFDF9" /><Text style={styles.primaryText}>Refine this room</Text></Pressable></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 35 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 22 }, step: { fontSize: 11, fontWeight: "900", letterSpacing: 1.6 }, title: { fontSize: 32, lineHeight: 38, fontWeight: "800" }, subtitle: { fontSize: 14, marginTop: 8, marginBottom: 20 }, preview: { height: 300, borderRadius: 24, overflow: "hidden", position: "relative" }, photo: { width: "100%", height: "100%" }, window: { position: "absolute", top: 30, right: 34, width: 115, height: 110, backgroundColor: "#DEE8E2", borderWidth: 8, borderColor: "#EFE7DA" }, sofa: { position: "absolute", left: 26, bottom: 42, width: 220, height: 62, borderRadius: 14, backgroundColor: "#75685C" }, plant: { position: "absolute", right: 40, bottom: 37, width: 19, height: 90, borderRadius: 10, backgroundColor: "#65705B" }, badge: { position: "absolute", left: 15, top: 15, flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: "rgba(39,36,33,0.78)", borderRadius: 10, paddingHorizontal: 10, paddingVertical: 7 }, badgeText: { color: "#FFFDF9", fontSize: 9, fontWeight: "900", letterSpacing: 1 }, note: { flexDirection: "row", alignItems: "center", gap: 10, borderWidth: 1, borderRadius: 17, padding: 14, marginTop: 15 }, noteText: { flex: 1, fontSize: 13, lineHeight: 19 }, sectionTitle: { fontSize: 19, fontWeight: "800", marginTop: 25, marginBottom: 5 }, history: { minHeight: 58, borderBottomWidth: 1, flexDirection: "row", alignItems: "center", gap: 11, paddingHorizontal: 6 }, activeHistory: { backgroundColor: "#F7EEE7", borderRadius: 12 }, dot: { width: 9, height: 9, borderRadius: 5 }, historyLabel: { fontSize: 14, fontWeight: "700" }, historyDate: { fontSize: 12, marginTop: 3 },   restored: { fontSize: 12, fontWeight: "700", marginTop: 10 }, connectionBanner: { flexDirection: "row", alignItems: "center", gap: 8, borderWidth: 1, borderRadius: 14, paddingHorizontal: 12, paddingVertical: 10, marginBottom: 15 }, connectionText: { flex: 1, fontSize: 12, lineHeight: 17 }, primary:
 { minHeight: 53, borderRadius: 17, marginTop: 24, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, primaryText: { color: "#FFFDF9", fontSize: 15, fontWeight: "800" }, state: { flex: 1, alignItems: "center", justifyContent: "center", gap: 14 }, stateText: { fontSize: 13 }, pressed: { opacity: 0.75, transform: [{ scale: 0.985 }] } });
