import { describe, expect, it } from "vitest";
import { allows, annualSavings, billingAccess, billingMessage, canPause, claimPurchase, editorCreditCost, formatPrice, getCachedPlan, hasAdvancedEntitlement, hdExportCost, paywallCopy, priceMatches, PRODUCTS, priorityAllowed, referralCode, refundState, remaining, setCachedPlan, spendCredits, usagePercent, validCredits, validPlan, validPromo, validReferral, videoCredits, wholeHomeCreditCost } from "../services/billing";
import { buildDesignDecisions, buildPreservationRules, normalizeDesignerRequest, styleCompatibility } from "../services/aiInteriorDesigner";

describe("AI interior designer contracts", () => {
  const room = { roomId: "room-1", roomType: "living-room", imageUrls: ["demo://room"], goals: ["rearrange" as const], preserveObjectIds: [] };
  it("normalizes bounded designer requests", () => { expect(normalizeDesignerRequest({ room, outputCount: 99, requestedChanges: Array(20).fill("change") }).outputCount).toBe(6); expect(normalizeDesignerRequest({ room }).preserveArchitecture).toBe(true); });
  it("keeps architecture-first decisions explicit", () => { expect(buildDesignDecisions(room)[0].category).toBe("architecture"); expect(buildPreservationRules([{ id: "sofa", label: "sofa" }], true)[0].mode).toBe("keep"); expect(styleCompatibility("modern", "minimal")).toBeGreaterThan(0.7); });
});

describe("advanced premium billing", () => {
  it("exposes transparent products and feature access", () => { expect(PRODUCTS.some((product) => product.id === "pro_annual")).toBe(true); expect(allows("free", "hd-export")).toBe(false); expect(allows("pro-plus", "video-walkthrough")).toBe(true); expect(formatPrice(999, "USD")).toContain("9.99"); });
  it("protects credit mutations and reports contextual recovery", () => { const wallet = { userId: "u1", designCredits: 3, hdCredits: 0, videoCredits: 0 }; expect(spendCredits(wallet, "designCredits", 2).designCredits).toBe(1); expect(() => spendCredits(wallet, "designCredits", 4)).toThrow("INSUFFICIENT_CREDITS"); expect(editorCreditCost("replace")).toBe(2); expect(billingMessage("NETWORK_ERROR")).toContain("unavailable"); expect(claimPurchase("purchase-1")).toBe(true); expect(claimPurchase("purchase-1")).toBe(false); });
  it("keeps usage and upgrade messaging understandable", () => { expect(usagePercent(2, 3)).toBeCloseTo(0.667, 2); expect(remaining(2, 3)).toBe(1); expect(paywallCopy("advanced-refinement").recommendedTier).toBe("pro"); });
  it("supports transparent savings, referrals, and lifecycle states", () => { expect(annualSavings(999, 7999)).toBe(3989); expect(hasAdvancedEntitlement("business", "team_workspace")).toBe(true); expect(validPromo({ code: "WELCOME", kind: "percent", value: 20, expiresAt: "2099-01-01", uses: 0 })).toBe(true); expect(validReferral(referralCode("user-1234"))).toBe(true); expect(billingAccess(2)).toBe("grace"); expect(canPause("active")).toBe(true); });
  it("protects server-authoritative billing state", () => { expect(priceMatches(999, 999)).toBe(true); expect(priceMatches(999, 1)).toBe(false); expect(validCredits(3)).toBe(true); expect(validCredits(-1)).toBe(false); expect(validPlan("pro")).toBe(true); expect(validPlan("gold")).toBe(false); expect(refundState("paid")).toBe("refunded"); expect(videoCredits(21)).toBe(3); expect(wholeHomeCreditCost(2)).toBe(4); expect(priorityAllowed("pro-plus")).toBe(true); setCachedPlan("billing-test", "pro", 1000); expect(getCachedPlan("billing-test")).toBe("pro"); expect(getCachedPlan("billing-test", Date.now() + 1001)).toBe(null); expect(hdExportCost).toBe(1); });
});
