import type { ReactNode } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

export function VisualCard({ children, style }: { children: ReactNode; style?: object }) { return <View style={[styles.card, style]}>{children}</View>; }
export function PrimaryButton({ title, onPress, icon, disabled = false }: { title: string; onPress: () => void; icon?: ReactNode; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.primary, pressed && styles.pressed, disabled && styles.disabled]}>{icon}<Text style={styles.primaryText}>{title}</Text></Pressable>; }
export function InlineError({ message, onRetry }: { message: string; onRetry?: () => void }) { return <View accessibilityRole="alert" style={styles.error}><Text style={styles.errorText}>{message}</Text>{onRetry ? <Pressable accessibilityRole="button" onPress={onRetry}><Text style={styles.retry}>Try again</Text></Pressable> : null}</View>; }
export function EmptyState({ title, body, action }: { title: string; body: string; action?: ReactNode }) { return <View style={styles.empty}><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyBody}>{body}</Text>{action}</View>; }
export function ProgressBar({ value }: { value: number }) { const progress = Math.max(0, Math.min(1, value)); return <View accessibilityLabel={`${Math.round(progress * 100)} percent complete`} style={styles.track}><View style={[styles.fill, { width: `${progress * 100}%` }]} /></View>; }
const styles = StyleSheet.create({ card: { backgroundColor: "#FFFDF9", borderRadius: 22, borderWidth: 1, borderColor: "#E5DED6" }, primary: { minHeight: 52, borderRadius: 16, paddingHorizontal: 18, backgroundColor: "#B9654A", alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 7 }, primaryText: { color: "#FFFDF9", fontSize: 14, fontWeight: "800" }, pressed: { opacity: 0.75, transform: [{ scale: 0.985 }] }, disabled: { opacity: 0.45 }, error: { backgroundColor: "#F7E3DE", borderRadius: 15, padding: 13, gap: 7 }, errorText: { color: "#A0443B", fontSize: 13, lineHeight: 18, fontWeight: "700" }, retry: { color: "#A0443B", fontSize: 13, fontWeight: "900" }, empty: { alignItems: "center", padding: 28, gap: 8 }, emptyTitle: { color: "#292522", fontSize: 20, fontWeight: "800", textAlign: "center" }, emptyBody: { color: "#746D66", fontSize: 14, lineHeight: 21, textAlign: "center", maxWidth: 290 }, track: { height: 7, borderRadius: 7, backgroundColor: "#E5DED6", overflow: "hidden" }, fill: { height: "100%", borderRadius: 7, backgroundColor: "#B9654A" } });
